### ISSUE TITLE
Enhancement: Use TelFit with Starfish and IGRINS data

### ISSUE THREAD

**Issue by gully** [kgullikson88/Telluric-Fitter#11]
There a lot of talk about telluric correction at the IGRINS workshop.  I think TelFit can help.  I also wondered if it could be used within Starfish to iteratively solve for the Telluric model simultaneously with the stellar and calibration parameters.  What do you think?

**Comment by kgullikson88** [comment]
That would be a lot of work, but should be doable and is really the "right" way to do this. I think you would have to write an entirely new fitter, probably modeled on how starfish does things, because there isn't an easy way to add stellar fitting to the likelihood function as it is now.

**Comment by gully** [comment]
This idea is probably out-of-scope for TelFit as it currently stands.  To do this right, someone would likely want to use Hamiltonian Monte Carlo, analogously to the [exoJAX](https://github.com/HajimeKawahara/exojax) project.  Alternatively one could compute the "profile likelihood" for stellar parameters given a fitted telluric model.  In either case this would be an entire research program and is not on the roadmap for telfit.
