### ISSUE TITLE
Build fails on Mac OS X 10.10 with Apple LLVM version 7.0.0

### ISSUE THREAD

**Issue by gully** [kgullikson88/Telluric-Fitter#12]
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

$ python --version
Python 2.7.10 :: Continuum Analytics, Inc.

$ conda list
# packages in environment at //anaconda/envs/legacy:
#
astropy                   1.0.5               np110py27_1
cython                    0.23.4                   py27_0
d2to1                     0.2.12.post1              <pip>
fortranformat             0.2.5                     <pip>
freetype                  2.5.5                         0
libpng                    1.6.17                        0
lockfile                  0.10.2                   py27_0
matplotlib                1.4.3               np110py27_3
numpy                     1.10.1                   py27_0
openssl                   1.0.2d                        0
pandas                    0.17.0              np110py27_0
pip                       7.1.2                    py27_0
pyparsing                 2.0.3                    py27_0
pyqt                      4.11.4                   py27_0
pysynphot                 0.9.7                     <pip>
python                    2.7.10                        2
python-dateutil           2.4.2                    py27_0
pytz                      2015.7                   py27_0
qt                        4.8.7                         1
readline                  6.2                           2
requests                  2.8.1                    py27_0
scipy                     0.16.0              np110py27_1
seaborn                   0.6.0               np110py27_0
setuptools                18.4                     py27_0
sip                       4.16.9                   py27_0
six                       1.10.0                   py27_0
sqlite                    3.8.4.1                       1
stsci.distutils           0.3.7                     <pip>
tk                        8.5.18                        0
wheel                     0.26.0                   py27_1
zlib                      1.2.8                         0

Error message:
```bash
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.5-x86_64-2.7
  copying src/TelluricFitter.py -> build/lib.macosx-10.5-x86_64-2.7
  copying src/MakeModel.py -> build/lib.macosx-10.5-x86_64-2.7
  copying src/DataStructures.py -> build/lib.macosx-10.5-x86_64-2.7
  copying src/MakeTape5.py -> build/lib.macosx-10.5-x86_64-2.7
  creating build/lib.macosx-10.5-x86_64-2.7/telfit
  copying src/telfit/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/telfit
  running build_ext
  Downloading data from http://www.as.utexas.edu/~kgulliks/media/data/aerlbl_v12.2_package.tar.gz and putting it in directory /Users/gully/.TelFit/
  Un-packing aer_v_3.2.tar.gz
  Un-packing aerlnfl_v2.6.tar.gz
  Un-packing aerlbl_v12.2.tar.gz
  error: Suitable compiler not found!

  ----------------------------------------
  Failed building wheel for TelFit
Failed to build TelFit
Installing collected packages: TelFit, nose, funcsigs, pbr, mock
  Running setup.py install for TelFit
    Complete output from command //anaconda/envs/legacy/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/11/l9cm4ns91k18tz3qt8bjlg3r0000gn/T/pip-build-q1bT6L/TelFit/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/11/l9cm4ns91k18tz3qt8bjlg3r0000gn/T/pip-FetUHR-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    Un-packing aer_v_3.2.tar.gz
    Un-packing aerlnfl_v2.6.tar.gz
    Un-packing aerlbl_v12.2.tar.gz
    error: Suitable compiler not found!

    ----------------------------------------
Command "//anaconda/envs/legacy/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/11/l9cm4ns91k18tz3qt8bjlg3r0000gn/T/pip-build-q1bT6L/TelFit/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/11/l9cm4ns91k18tz3qt8bjlg3r0000gn/T/pip-FetUHR-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/11/l9cm4ns91k18tz3qt8bjlg3r0000gn/T/pip-build-q1bT6L/TelFit
```

**Comment by gully** [comment]
Boom.  I have a workaround for this.  The above failure is due to an incompatible `gcc` version:

```bash
$ gcc --version
gcc-5 (Homebrew gcc 5.2.0) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Results in a suscessful TelFit install.

```bash
Successfully built TelFit
Installing collected packages: TelFit, nose, funcsigs, pbr, mock
Successfully installed TelFit-1.3.2 funcsigs-0.4 mock-1.3.0 nose-1.3.7 pbr-1.8.1
```

**Comment by kgullikson88** [comment]
That is weird that it didn't find the other gcc version. The setup script should have been able to find it as long as the command `gcc --help` runs without error. I'm glad to see you figured it out though.

**Comment by dyq0811** [comment]
> Boom. I have a workaround for this. The above failure is due to an incompatible `gcc` version:
> 
> ```shell
> $ gcc --version
> gcc-5 (Homebrew gcc 5.2.0) 5.2.0
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```
> 
> Results in a suscessful TelFit install.
> 
> ```shell
> Successfully built TelFit
> Installing collected packages: TelFit, nose, funcsigs, pbr, mock
> Successfully installed TelFit-1.3.2 funcsigs-0.4 mock-1.3.0 nose-1.3.7 pbr-1.8.1
> ```

Hello, could you please share how you install the specific version (5.2.0) of gcc? I installed brew then installed gcc, but the version is different and I still cannot install Telfit.
