### ISSUE TITLE
setup.py build attempts to download aerlbl_v12.2_package.tar.gz, no file exists

### ISSUE THREAD

**Issue by jlamoure** [kgullikson88/Telluric-Fitter#16]
Below is failed output. I do not think there are files anymore at http://www.as.utexas.edu/~kgulliks/media/data. However, if aerlbl_v12.2_package.tar.gz has been copied over from a previous successful download and extracted in ~/.TelFit, build script proceeds (to issue #15 for me).

```
$ > python setup.py build
running build
running build_py
running build_ext
Downloading data from http://www.as.utexas.edu/~kgulliks/media/data/aerlbl_v12.2_package.tar.gz and putting it in directory /home/jacob/.TelFit/

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "setup.py", line 334, in <module>
    package_dir={'': 'src'}
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 270, in run
    MakeLBLRTM()
  File "setup.py", line 207, in MakeLBLRTM
    subprocess.check_call(['tar', '-xzf', outfile, '-C', TELLURICMODELING])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', '-xzf', '/home/jacob/.TelFit/aerlbl_package.tar.gz', '-C', '/home/jacob/.TelFit/']' returned non-zero exit status 2

```

**Comment by mlopezmorales** [comment]
I am having the same problem. Could you please let us know when/where the file is up? Thank you for making this code public.

**Comment by kgullikson88** [comment]
I am currently working with my old university to get it hosted more permanently, but progress has been slow. In the meantime, you can try the updated version of lblrtm from [here](http://rtweb.aer.com/lblrtm_code.html). 

Then, just put the tar file in `~/.TelFit` and try building. I can't guarantee that everything will work with the 12.4 version, but it probably will...

**Comment by kgullikson88** [comment]
Please check if PR #17 fixes the issue, and comment either here or on the PR.

https://github.com/kgullikson88/Telluric-Fitter/pull/17

**Comment by jlamoure** [comment]
#17 fixes the issue for me. Thanks for keeping the packages online!
