### ISSUE TITLE
Remove lingering Python 2 print statements

### ISSUE THREAD

**Issue by gully** [kgullikson88/Telluric-Fitter#35]
@reillymilburn points out that line 189 of Fit.py contains a python 2 print statement.  

```python
File "Fit.py", line 189
print "\n***************************\nFitting order %i: " % (i)
^
```

We are seeking volunteers to go through the code base to identify and replace such lingering print statements with `print()` functions, to be compatible with Python3.  We invite pull requests to resolve this and possibly other legacies of telfit's python2 provenance.

**Comment by shihyuntang** [comment]
@gully 
Haha, there are actually two print statement in that Fit.py file.
I did fix those two print statement lines also in the pull request "Reduce resolution2" #33.
Do we want me two split that to two? one for move to use "Reduce resolution2" and one for fixing the print statements?

**Comment by gully** [comment]
Oh perfect!  No need to split that PR.  I will have to spot-check that PR and merge it.  I will link this Issue to close when the PR is merged.  Thank you @shihyuntang :pray:
