### ISSUE TITLE
TelFit stopped working - Unlocked directory not found

### ISSUE THREAD

**Issue by reillymilburn** [kgullikson88/Telluric-Fitter#46]
I have been using TelFit consistently for a while now, but have encountered a new error I am unsure how to deal with. When I try and run TelFit on my data, I receive this warning indefinitely:

WARNING:root:Un-locked directory not found! Waiting 10 seconds...

As far as I know, I have not changed anything with my computer. It is possible my computer auto-updated to the newest version of Mac OS. Could that be the issue here? What are your recommendations for getting TelFit working again?

UPDATE:

I also receive this warning when importing TelFit:

/Users/reilly/opt/anaconda3/envs/telenv/lib/python3.9/site-packages/pysynphot/locations.py:46: UserWarning: PYSYN_CDBS is undefined; functionality will be SEVERELY crippled.
  warnings.warn("PYSYN_CDBS is undefined; functionality will be SEVERELY "
/Users/reilly/opt/anaconda3/envs/telenv/lib/python3.9/site-packages/pysynphot/locations.py:345: UserWarning: Extinction files not found in extinction
  warnings.warn('Extinction files not found in %s' % (extdir, ))

Thanks, 
Reilly

**Comment by reillymilburn** [comment]
This looks to be a more in depth error: 

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-7-d272c72c4a9a> in <module>
     44     if __name__ == "__main__":
     45         # Initialize fitter
---> 46         fitter = TelluricFitter(debug=True)
     47 
     48         #Set the observatory location with a keyword

~/opt/anaconda3/lib/python3.8/site-packages/TelluricFitter.py in __init__(self, debug, debug_level, print_lblrtm_output)
    107         self.debug = debug
    108         self.debug_level = debug_level  #Number from 1-5, with 5 being the most verbose
--> 109         self.Modeler = MakeModel.Modeler(debug=self.debug, print_lblrtm_output=print_lblrtm_output)
    110         self.parvals = [[] for i in range(len(self.parnames))]
    111         self.chisq_vals = []

~/opt/anaconda3/lib/python3.8/site-packages/MakeModel.py in __init__(self, debug, TelluricModelingDirRoot, nmolecules, print_lblrtm_output)
    133 
    134         #Determine working directories
--> 135         self.FindWorkingDirectory()
    136         TelluricModelingDir = self.TelluricModelingDir
    137         ModelDir = self.ModelDir

~/opt/anaconda3/lib/python3.8/site-packages/MakeModel.py in FindWorkingDirectory(self)
    319             if not found:
    320                 logging.warn("Un-locked directory not found! Waiting 10 seconds...")
--> 321                 time.sleep(10)
    322         logging.debug('Telluric Modeling Directory = {}'.format(TelluricModelingDir))
    323         logging.debug('Mode Directory = {}'.format(ModelDir))

**Comment by kgullikson88** [comment]
If I remember correctly, the telfit working directory is `~/.telfit`. From the traceback, it looks like you can verify that if you turn up the logging level to debug. 

But basically, I believe that can happen if telfit crashes too many times. You have to manually go into that working directory and delete the lock files yourself.

**Comment by reillymilburn** [comment]
Lock files deleted and it seems to be working again! Thanks so much! :')

-Reilly

**Comment by gully** [comment]
I'll consider this Issue closed, since a workaround appears to resolve the problem.  Feel free to re-open if you think we should address the root cause.
