### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sblunt** [kgullikson88/Telluric-Fitter#47]
Hey there! Thanks for writing this awesome looking package. I'm trying to install it on a linux machine and getting an error.

I git cloned and then attempted install using:

`python setup.py build install`

Here's the full trace:

`/data/user/sblunt/miniconda3/lib/python3.8/site-packages/setuptools/dist.py:757: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
running build
running build_py
creating build/lib.linux-x86_64-cpython-38
copying src/TelluricFitter.py -> build/lib.linux-x86_64-cpython-38
copying src/MakeModel.py -> build/lib.linux-x86_64-cpython-38
copying src/DataStructures.py -> build/lib.linux-x86_64-cpython-38
copying src/MakeTape5.py -> build/lib.linux-x86_64-cpython-38
creating build/lib.linux-x86_64-cpython-38/telfit
copying src/telfit/__init__.py -> build/lib.linux-x86_64-cpython-38/telfit
running build_ext
Un-packing aer_v_3.2.tar.gz
tar: aer_v_3.2/RELEASE_NOTES_aer_linefile: Cannot open: File exists
tar: aer_v_3.2/line_file/aer_v_3.2: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/01_H2O/01_H2O: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/01_H2O/01_h2o_161_only: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/01_H2O/01_h2o_162_excl: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/01_H2O/01_h2o_162_only: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/01_H2O/01_h2o_171_only: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/01_H2O/01_h2o_172_only: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/01_H2O/01_h2o_181_only: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/01_H2O/01_h2o_182_only: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/02_CO2/02_CO2: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/03_O3/03_O3: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/04_N2O/04_N2O: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/05_CO/05_CO: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/06_CH4/06_CH4: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/07_O2/07_O2: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/08_NO/08_NO: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/09_SO2/09_SO2: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/10_NO2/10_NO2: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/11_NH3/11_NH3: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/12_HNO3/12_HNO3: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/13_OH/13_OH: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/14_HF/14_HF: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/15_HCL/15_HCL: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/16_HBR/16_HBR: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/17_HI/17_HI: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/18_CLO/18_CLO: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/19_OCS/19_OCS: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/20_H2CO/20_H2CO: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/21_HOCL/21_HOCL: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/22_N2/22_N2: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/23_HCN/23_HCN: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/24_CH3CL/24_CH3CL: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/25_H2O2/25_H2O2: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/26_C2H2/26_C2H2: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/27_C2H6/27_C2H6: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/28_PH3/28_PH3: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/29_COF2/29_COF2: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/30_SF6/30_SF6: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/31_H2S/31_H2S: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/32_HCOOH/32_HCOOH: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/33_HO2/33_HO2: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/34_O/34_O: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/35_CLONO2/35_CLONO2: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/36_NO+/36_NO+: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/37_HOBr/37_HOBr: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/38_C2H4/38_C2H4: Cannot open: File exists
tar: aer_v_3.2/line_files_By_Molecule/39_CH3OH/39_CH3OH: Cannot open: File exists
tar: Exiting with failure status due to previous errors
Traceback (most recent call last):
  File "setup.py", line 329, in <module>
    setup(name='TelFit',
  File "/data/user/sblunt/miniconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/data/user/sblunt/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/data/user/sblunt/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/data/user/sblunt/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/data/user/sblunt/miniconda3/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/data/user/sblunt/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/data/user/sblunt/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 136, in run
    self.run_command(cmd_name)
  File "/data/user/sblunt/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/data/user/sblunt/miniconda3/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/data/user/sblunt/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "setup.py", line 293, in run
    MakeLBLRTM()
  File "setup.py", line 237, in MakeLBLRTM
    subprocess.check_call(["tar", "-xzf", '{}{}'.format(TELLURICMODELING, fname), '-C', TELLURICMODELING])
  File "/data/user/sblunt/miniconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', '-xzf', '/home/sblunt/.TelFit/aer_v_3.2.tar.gz', '-C', '/home/sblunt/.TelFit/']' returned non-zero exit status 2.`

I tried updating `setuptools`, as a previous issue suggested, but no luck.

**Comment by gully** [comment]
Hi @sblunt thanks for your interest in TelFit! Installing TelFit can be notoriously brittle.  I don't have a quick answer for your particular issue, but it looks vaguely familiar.  I remember some amount of manual inspection of the .tar files was useful once.  My broad guidance is spot check the [existing Issues](https://github.com/kgullikson88/Telluric-Fitter/issues?q=is%3Aissue+label%3Ainstallation), even if they are closed, but it appears that you may have already done that.  Another route is to try pip install, which was updated recently enough that it may work.

**Comment by sblunt** [comment]
Thanks! I had tried installing with pip before but just tried it again and it seems to have worked! *shrug* thanks :)

**Comment by gully** [comment]
Terrific news! The pip installation method remains experimental so let us know if you encounter any further friction points.  Thanks again for your patience.  

For better or worse I'm going to consider this issue resolved for now, even though we never arrived at the root cause.  Simply put, TelFit installation is brittle due to some complex Fortran dependencies that are often violated in a platform-dependent and customization-dependent way.

**Comment by sblunt** [comment]
Sounds good, thanks for your help! :)
