### ISSUE TITLE
SciPy.mat is obsolete

### ISSUE THREAD

**Issue by StuartLittlefair** [kgullikson88/Telluric-Fitter#57]
Used in the line below, and perhaps others, `scipy.mat` is no longer present in SciPy v12.

https://github.com/kgullikson88/Telluric-Fitter/blob/7ae98db278525e157d2d0abaf4697e2fe778d6bc/src/TelluricFitter.py#L62

This function is just an alias for `numpy.asmatrix` so a drop-in replacement of `from numpy import asmatrix as mat` should be an easy fix

**Comment by kgullikson88** [comment]
Thanks for pointing this out and identifying the fix. Please make a quick PR with the change
